-- CREATE EMPLOYEES DATABASE
CREATE DATABASE IF NOT EXISTS EMPLOYEES;

-- SWITCH THE DATABASE
USE EMPLOYEES;

-- CREATE EMP TABLE
CREATE TABLE EMP(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(255) NOT NULL,
DEPARTMENT VARCHAR(255) NOT NULL,
SALARY DECIMAL NOT NULL);

-- INSERT SAMPLE DATA
INSERT INTO EMP VALUES
(1,'SRAVANI','SRAVANI@GMAIL.COM',50000),
(2,'VEERAVENI','VEERAVENI@GMAIL.COM',45900),
(3,'LAVANYA','LAVANYA@GMAIL.COM',20000),
(4,'SUNIL','SUNIL@GMAIL.COM',23000),
(5,'VARUN','VARUN@GMAIL.COM',90000);

-- STORED PROCEDURE: GET ALL EMPLOYEES IN A GIVEN DEPARTMENT
DELIMITER $$

CREATE PROCEDURE GETEMPLOYEEBYDEPT(IN DEPARTMENT VARCHAR(30))
BEGIN
SELECT EMP_NAME,SALARY
FROM EMP
WHERE DEPARTMENT=DEPARTMENT;
END $$

DELIMITER ;
-- USE THE FUCTION
CALL GETEMPLOYEEBYDEPT('IT');

/*
EMP_NAME   SALARY
-----------------
SRAVANI	   50000
VEERAVENI  45900
LAVANYA	   20000
SUNIL	   23000
VARUN	   90000
*/

-- STORED FUNCTION: GET AVEARAGE SALARY OF A DEPARTMENT
DELIMITER $$

CREATE FUNCTION AVGDEPTSALARY(DEPARTMENT VARCHAR(30))
RETURNS INT 
DETERMINISTIC
BEGIN
DECLARE AVG_SALARY DECIMAL;
SELECT AVG(SALARY)INTO AVG_SALARY
FROM EMP
WHERE DEPARTMENT=DEPARTMENT;
RETURN AVG_SALARY;
END $$

DELIMITER ;

-- USE THE FUCTION
SELECT AVGDEPTSALARY('HR') AS HR_AVERAGE_SALARY;

/*
HR_AVERAGE_SALARY
-----------------
45780
*/